# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 338e9fb12f72f135ea3aa36a18511455ef6b1f1634a7210b38136614121d720d232723aca5c345902777d105e761d9741cf8743e11b9f476af0603dcf2817b5f

test:
  secret_key_base: 4318cd7516e70e6f2824b4075051411e8d5f78e9b0b9807e9feec98422cc02f4d5b4a8080df95563686740ccf9d45e3add306420edcd8c4b8790e3cb1debfc42

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
